CREATE DATABASE  IF NOT EXISTS `dcode`;
drop database dcode;
create database dcode;
use dcode;

DROP TABLE IF EXISTS daily_usage_statistics;

CREATE TABLE daily_usage_statistics (
  pk int(11) NOT NULL AUTO_INCREMENT,
  date date NOT NULL,
  visits int(10) unsigned zerofill NOT NULL,
  PRIMARY KEY (pk),
  UNIQUE KEY date_UNIQUE (date)
) AUTO_INCREMENT=1 DEFAULT ;

DROP TABLE IF EXISTS task_type;

CREATE TABLE task_type (
  ID int(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(50) NOT NULL,
  CODE varchar(10) NOT NULL,
  PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1 DEFAULT;

INSERT INTO task_type VALUES 
(1,'Client Service','CS'),
(2,'Firm Initiative','FI');

Create table log(
Id int NOT NULL auto_increment,
description varchar(255),
details varchar(255),
user varchar(50),
primary key (ID)
) auto_increment=1;

Create table suggestion(
Id int NOT NULL auto_increment,
description varchar(255),
details varchar(255),
user varchar(50),
primary key (ID)
) auto_increment=1;

CREATE TABLE SERVICE_LINE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(20) NOT NULL,
  Description varchar(50) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (Name),
  UNIQUE KEY (Description)
) auto_increment = 1;

Create TABLE USERS(
	ID INT NOT NULL auto_increment,
	FIRST_NAME varchar(50) NULL,
	LAST_NAME varchar(50) NULL,
	DESIGNATION varchar(50) NULL,
	EMAIL_ID varchar(255) NOT NULL,
	PROJECT_NAME varchar(255) NULL,
	PROJECT_CODE varchar(255) NULL,
	PROJECT_MANAGER_NAME varchar(255) NULL, 
	MANAGER_EMAIL_ID varchar(255) NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID)
) auto_increment=1;

CREATE TABLE TASKS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  PROJECT_NAME varchar(50) NOT NULL,
  TASK_NAME varchar(50) DEFAULT NULL,
  PROJECT_WBS_Code varchar(50) NOT NULL,
  TYPE varchar(100) DEFAULT NULL,
  TASK_TYPE_ID int(11) DEFAULT NULL,
  DETAILS varchar(255) DEFAULT NULL,
  HOURS int(11) DEFAULT NULL,
  COMMENTS varchar(255) DEFAULT NULL,
  GIFTS bit(1) DEFAULT NULL,
  ONBOARDING_DATE datetime DEFAULT NULL,
  SERVICE_LINE_ID int(11) NOT NULL,
  DUE_DATE datetime DEFAULT NULL,
  STATUS varchar(20) DEFAULT NULL,
  STATUS_DATE datetime DEFAULT NULL,
  CREATED_BY varchar(100) DEFAULT NULL,
  CREATED_ON datetime DEFAULT NULL,
  UPDATED_BY varchar(100) DEFAULT NULL,
  UPDATED_ON datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY `USER_ID` (USER_ID),
  KEY `SERVICE_LINE_ID` (SERVICE_LINE_ID),
  KEY `TASK_TYPE_ID` (TASK_TYPE_ID),
  CONSTRAINT tasks_ibfk_3 FOREIGN KEY (TASK_TYPE_ID) REFERENCES task_type (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT tasks_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES users (ID),
  CONSTRAINT tasks_ibfk_2 FOREIGN KEY (SERVICE_LINE_ID) REFERENCES service_line (ID)
   )auto_increment=1;

CREATE TABLE TASKAPPLICANTS(
	ID INT NOT NULL auto_increment,
	TASK_ID INT NOT NULL,
	APPLICANT_ID INT NOT NULL,
	STATEMENT_OF_PURPOSE varchar(500) DEFAULT NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID),
FOREIGN KEY(APPLICANT_ID) references USERS(ID),
FOREIGN KEY(TASK_ID) references TASKS(ID)
)auto_increment=1;

CREATE TABLE APPROVEDAPPLICANT(
	ID INT NOT NULL auto_increment,
	APPLICANT_ID INT NOT NULL,
	TASK_ID	int NOT NULL,
	HOURS_WORKED decimal(5, 1) NULL,
	RATING varchar(50) NULL,
	WORK_AGAIN bit NULL,
	POINTS int NULL,
	COMMENTS varchar(255) NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID),
FOREIGN KEY(APPLICANT_ID) references USERS(ID),
FOREIGN KEY(TASK_ID) references TASKS(ID)
)auto_increment=1;


CREATE TABLE SKILLS(
	ID INT NOT NULL auto_increment,
	VALUE varchar(200) NOT NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID)
)auto_increment=1;

CREATE TABLE APPLICANTSKILLS(
	ID INT NOT NULL auto_increment,
	APPLICANT_ID INT NOT NULL,
	SKILL_ID INT NOT NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID),
FOREIGN KEY(APPLICANT_ID) references USERS(ID),
FOREIGN KEY(SKILL_ID) references SKILLS(ID)
)auto_increment=1;


CREATE TABLE TASKSKILLS(
	ID INT NOT NULL auto_increment,
	TASK_ID INT NOT NULL,
	SKILL_ID INT NOT NULL,
	STATUS varchar(20) NULL,
	STATUS_DATE datetime NULL,
	CREATED_BY varchar(100) NULL,
	CREATED_ON datetime NULL,
	UPDATED_BY varchar(100) NULL,
	UPDATED_ON datetime NULL,
PRIMARY KEY(ID),
FOREIGN KEY(TASK_ID) REFERENCES TASKS(ID),
FOREIGN KEY(SKILL_ID) references SKILLS(ID)
)auto_increment = 1;


CREATE TABLE NOTIFICATION_SUBSCRIPTION (
  NOTIFICATION_SUBSCRIPTION_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  SUBSCRIPTION_STATUS bit(1) NOT NULL,
  PRIMARY KEY (NOTIFICATION_SUBSCRIPTION_ID),
  UNIQUE KEY USER_ID_UNIQUE (USER_ID),
  UNIQUE KEY notification_subscription_id_UNIQUE (NOTIFICATION_SUBSCRIPTION_ID),
  CONSTRAINT FK_USERS_NOTIFICATION_STATUS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE NO ACTION
)AUTO_INCREMENT = 1;

CREATE TABLE daily_usage_statistics (
  pk int(11) NOT NULL AUTO_INCREMENT,
  date date NOT NULL,
  visits int(10) unsigned zerofill NOT NULL,
  PRIMARY KEY (pk),
  UNIQUE KEY date_UNIQUE (date)
) AUTO_INCREMENT=1;

INSERT INTO `service_line` VALUES 
(1,'DD','Deloitte Digital'),
(2,'SI','System Integration'),
(3,'Oracle', 'Oracle'),
(4,'Cloud', 'Cloud'),
(5,'SAP', 'SAP'),
(6,'AIM', 'AIM'),
(7,'AMS', 'AMS');


INSERT INTO SKILLS(ID,VALUE,STATUS,STATUS_DATE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON) values
(1,'ITS-Application / Vendor Selection / Rationalization','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(2,'3M/Medical Coding & Reimbursement','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(3,'Ab Initio ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(4,'Accessability Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(5,'Adobe Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(6,'Adobe Analytics','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(7,'Adobe Campaign','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(8,'Adobe CQ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(9,'Adobe CQ Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(10,'Adobe CQ Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(11,'Adobe flex','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(12,'Adobe Livecycle','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(13,'Adobe Test & Target','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(14,'Agile PLM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(15,'Agile Software Development Methodology','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(16,'Amazon Web Services (AWS)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(17,'Anaplan ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(18,'Android Development','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(19,'Angular JS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(20,'Apache Flume','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(21,'Apache Hadoop','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(22,'Apache Hive','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(23,'Apache Sqoop','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(24,'Apigee','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(25,'Appian','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(26,'Apple iOS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(27,'Application Architecture','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(28,'Aptitude DAP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(29,'Apttus','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(30,'Apttus Advanced Workflows & Approvals','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(31,'Apttus Configure Price Quote (CPQ)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(32,'Argus Safety Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(33,'Arisg','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(34,'ASP.net','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(35,'Automation Anywhere ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(36,'Automation Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(37,'Automation Testing  QTP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(38,'Automation Testing Selenium','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(39,'Autonomy idol','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(40,'Autonomy Idol Search','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(41,'Azure Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(42,'BackboneJS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(43,'Batch Monitoring','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(44,'Big Machines','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(45,'Biz Talk','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(46,'Blaze','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(47,'Blockchain','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(48,'Blockchain Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(49,'Blue Prism','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(50,'Blueprism Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(51,'Business Analysis','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(52,'C#','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(53,'Callidus','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(54,'Cast Iron','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(55,'Chatbot/NLP Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(56,'Cloud Financial','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(57,'Cloud Infrastructure Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(58,'Cloud Integration','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(59,'Cloud Manufacturing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(60,'Cloud Procurement','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(61,'Cloud Project Portfolio','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(62,'Cloud Projects','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(63,'Cloud Supply Chain','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(64,'Cloud Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(65,'Cloud Testing ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(66,'CloudCraze Commerce on Salesforce','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(67,'Cloudera ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(68,'Cobol','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(69,'Collibra','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(70,'Control M','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(71,'Corticon','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(72,'Creative Direction','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(73,'Crystal Reports','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(74,'CSS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(75,'Cutover','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(76,'Data Analytics','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(77,'Data Scientist','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(78,'Data Factory','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(79,'IBM DB2 DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(80,'DB2 Developer','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(81,'Delivery Manager','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(82,'Dell Boomi','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(83,'Dell Boomi Testing ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(84,'Demandware','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(85,'Deployment','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(86,'Dev Ops','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(87,'Digital Asset Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(88,'Digital Front End Development','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(89,'Digital Producer','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(90,'Digital User Experience','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(91,'Docker','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(92,'Dot Net with Angular JS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(93,'Drupal','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(94,'Duck Creek','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(95,'Ebao','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(96,'Ebao Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(97,'EBS Apps DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(98,'EBS BAM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(99,'EBS Cloud RICEW','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(100,'EBS Demantra','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(101,'EBS Discrete Manufacturing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(102,'EBS Finance','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(103,'EBS Fusion','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(104,'EBS HCM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(105,'EBS HCM Fusion','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(106,'EBS Manufacturing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(107,'EBS OAF','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(108,'EBS Order Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(109,'EBS ORMB','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(110,'EBS OTC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(111,'EBS OTL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(112,'EBS Process Manufacturing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(113,'EBS Projects','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(114,'EBS PTC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(115,'EBS PTM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(116,'EBS PTP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(117,'EBS Retail','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(118,'EBS RICEW','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(119,'EBS RTR','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(120,'EBS SCM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(121,'EBS SOA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(122,'EBS SOA Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(123,'EBS SOA Security','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(124,'SQL DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(125,'EBS TPM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(126,'EJB Frameworks','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(127,'EMC Documentum','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(128,'ENDECA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(129,'EPIC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(130,'Epic Ambulatory','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(131,'Epic Epicenter','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(132,'Epic IP ClinDoc','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(133,'Epic OpTime','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(134,'Epic Radiant','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(135,'Epic Willow','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(136,'ETL Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(137,'FileNet Certified Professional (FCP)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(138,'Force Heroku','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(139,'Functional Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(140,'Google Cloud Platform','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(141,'Github','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(142,'Google Analytics','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(143,'Google Android','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(144,'Groovy','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(145,'Guidewire','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(146,'Guidewire Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(147,'Heroku','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(148,'Hewlett Packard UNIX (HPUX)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(149,'Hibernate ORM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(150,'HL7','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(151,'HL7 Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(152,'Hortonworks Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(153,'HP Exstream','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(154,'HP Quality Center','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(155,'HTML','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(156,'HTML 5','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(157,'SAP Hybris','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(158,'Hybris Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(159,'Hyperion','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(160,'Hyperion Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(161,'Hyperion Essbase','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(162,'Hyperion Financial Data Quality Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(163,'Hyperion Financial Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(164,'Hyperion Financial Reporting','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(165,'HYPERION P&E','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(166,'Hyperion Planning','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(167,'Hyperion Profitability and Cost Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(168,'Ibatis','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(169,'Ibatis ORM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(170,'IBM Bluemix','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(171,'IBM BPM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(172,'IBM Cognos','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(173,'IBM Cognos BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(174,'IBM Cognos Planning','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(175,'IBM Cognos TM2','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(176,'IBM Datastage','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(177,'IBM IIB','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(178,'IBM Information Management System','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(179,'IBM Infosphere Datastage','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(180,'IBM Infosphere MDM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(181,'IBM Infosphere MDM Server','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(182,'IBM Infosphere Quality Stage','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(183,'IBM Initiate','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(184,'IBM Initiate MDM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(185,'IBM Mainframe','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(186,'IBM Message Broker','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(187,'IBM MQ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(188,'IBM ODM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(189,'IBM Rational Developworks','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(190,'IBM Rational Team Concert','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(191,'IBM SPSS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(192,'IBM Sterling','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(193,'IBM Transformation Extender','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(194,'IBM Websphere','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(195,'IBM Websphere Commerce','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(196,'IBM Websphere Datapower','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(197,'IBM Websphere Integration','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(198,'IBM Websphere Message Broker','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(199,'IBM Websphere Portal','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(200,'IBM Websphere Service Registry & Repository','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(201,'Ilog','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(202,'Informatica Power center','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(203,'Informatica Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(204,'Informatica Big Data Edition(BDE)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(205,'Informatica Big Data Management (BDM)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(206,'Informatica Cloud Data Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(207,'Informatica Data Quality','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(208,'Informatica INFA 10','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(209,'Informatica MDM ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(210,'Informatica MDM Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(211,'Informatica Siperian MDM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(212,'Infrastructure','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(213,'Infrastructure and Application Integration Framework','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(214,'Inquira','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(215,'Integration Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(216,'Interwoven','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(217,'IoT (Internet of Things)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(218,'IT Strategy','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(219,'IT Strategy Business Model','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(220,'IT Transformation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(221,'ITBM - IT Governance, Operating and Delivery Models','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(222,'ITBPM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(223,'ITMA - Command Center Opertaions','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(224,'ITMA - Financial Modeling','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(225,'ITMA - Infrastructure Readiness','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(226,'ITMA - IT Due Diligence','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(227,'ITMA - Planning and Readiness','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(228,'ITMA - Strategy','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(229,'ITMA - TSA Planning and Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(230,'ITS - Agile Advisory','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(231,'ITS - Application / Vendor Selection / Rationalization','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(232,'ITS - Business Case Development','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(233,'ITS - Digital Stratgey','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(234,'ITS - Digital Transformation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(235,'ITS - IT Cost Reduction','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(236,'ITS - IT Transformation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(237,'ITS - Operating Model','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(238,'ITS - Project Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(239,'ITSM process','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(240,'Japanese','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(241,'Jaspersoft','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(242,'JAVA J2EE','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(243,'JAVA J2EE with Angular JS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(244,'JAVA J2EE with Guidewire','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(245,'Javascript','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(246,'Jboss Fuse','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(247,'JBPM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(248,'JDE CNC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(249,'JDE Distribution','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(250,'JDE Financial','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(251,'JDE Manufacturing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(252,'JDE Payroll','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(253,'JDE Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(254,'Jenkins','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(255,'Jira','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(256,'Jive','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(257,'Jquery','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(258,'Jrules','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(259,'Json','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(260,'Kafka','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(261,'Kofax','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(262,'Lawson Financial','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(263,'Learning Content/Document Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(264,'Legacy Modernization Testing ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(265,'Liferay','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(266,'Linux Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(267,'Machine Learning','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(268,'Magento','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(269,'Mainframe Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(270,'Majesco','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(271,'Manual Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(272,'Mapreduce','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(273,'Matlab ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(274,'MDM Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(275,'Medallia','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(276,'Microservices','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(277,'Microsoft .Net','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(278,'Microsoft Access (MS ACCESS)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(279,'Microsoft Azure','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(280,'Microsoft Dynamics AX CRM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(281,'Microsoft Excel(MS EXCEL)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(282,'Microsoft Office 366','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(283,'Microsoft Office Specialist (MSO)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(284,'Microsoft PL/SQL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(285,'Microsoft Power BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(286,'Microsoft Powerpoint','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(287,'Microsoft Sharepoint','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(288,'Microsoft SQL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(289,'Microsoft SQL Server','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(290,'Microsoft SSAS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(291,'Microsoft SSIS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(292,'Microsoft SSRS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(293,'Microsoft Visual Studio .NET','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(294,'Micro Strategy ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(295,'Micro Strategy Report Services','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(296,'Mobile Automation Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(297,'Mobile Technology Services Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(298,'Mongo DB','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(299,'MQ Series','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(300,'MS SQL DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(301,'Mulesoft','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(302,'Mulesoft Testing ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(303,'MVC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(304,'MY SQL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(305,'MY SQL DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(306,'nCino','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(307,'Netbackup','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(308,'Netbackup Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(309,'Netsuite','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(310,'Netsuite Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(311,'Networking (Security/Routing/Switching)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(312,'Node.JS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(313,'ODI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(314,'Open Source ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(315,'Open Text','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(316,'Open Text Content Server','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(317,'Open Text Streamserve','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(318,'OpenText (extended ECM for SAP)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(319,'Oracle - ATG Web Commerce','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(320,'Oracle Account Reconciliation Cloud Service','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(321,'Oracle App Development Framework (ADF)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(322,'Oracle Argus','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(323,'Oracle BI Cloud Service','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(324,'Oracle BI Publisher','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(325,'Oracle Cloud CRM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(326,'Oracle Cloud Incentive Compensation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(327,'Oracle Data Integrator','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(328,'Oracle Data Relationship Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(329,'Oracle DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(330,'Oracle EBS Customer Data Hub','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(331,'Oracle EBS Data Quality','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(332,'Oracle EBS Product Data Hub','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(333,'Oracle ECM UCM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(334,'Oracle Eloqua','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(335,'Oracle Exadata DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(336,'Oracle Financial Consolidation and Close Cloud Service','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(337,'Oracle OBIA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(338,'Oracle OBIA-OBIEE','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(339,'Oracle OBIEE','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(340,'Oracle OBIEE Answers','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(341,'Oracle OBIEE Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(342,'Oracle OFSAA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(343,'Oracle PaaS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(344,'Oracle PL/SQL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(345,'Oracle Policy Automation (OPA)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(346,'Oracle RDBMS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(347,'Oracle Reports','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(348,'Oracle Service Cloud Agent Desktop','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(349,'Oracle Workflow','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(350,'Pega','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(351,'Pentaho ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(352,'Performance Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(353,'Performance Testing Jmeter','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(354,'PERL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(355,'PHP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(356,'Pig','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(357,'Pivotal','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(358,'PMO','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(359,'PMO/ITIL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(360,'Policy Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(361,'Power BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(362,'Primavera','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(363,'Project Manager','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(364,'PS AM/GL/PC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(365,'PS AM-COSTING','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(366,'PS AP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(367,'PS AR-BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(368,'PS Campus Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(369,'PS Campus Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(370,'PS DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(371,'PS Financials','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(372,'PS FSCM Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(373,'PS FSCM Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(374,'PS GL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(375,'PS GM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(376,'PS HCM Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(377,'PS HCM Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(378,'PS SCM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(379,'PS Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(380,'Python','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(381,'Qliksense ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(382,'Qlikview','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(383,'R Studio R programming','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(384,'R Studio Shiny','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(385,'R Studio Shiny Server','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(386,'React.js','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(387,'Red Hat ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(388,'Release Management ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(389,'REST webservices','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(390,'Right Now','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(391,'ROM Estimation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(392,'RPA Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(393,'Ruby On Rails','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(394,'Rule Engine Expert','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(395,'SAAS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(396,'Salesforce Debugging','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(397,'Salesforce Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(398,'Salesforce.com Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(399,'Salesforce.com Analytics','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(400,'Salesforce.com Apex Development','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(401,'Salesforce.com Architecture','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(402,'Salesforce.com Basic','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(403,'Salesforce.com Communities','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(404,'Salesforce.com Consoles','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(405,'Salesforce.com Customer Development','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(406,'Salesforce.com Data','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(407,'Salesforce.com Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(408,'Salesforce.com Heroku','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(409,'Salesforce.com Knowledge','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(410,'Salesforce.com Lightning','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(411,'Salesforce.com Marketing Cloud','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(412,'Salesforce.com Pardot','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(413,'Salesforce.com Project Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(414,'Salesforce.com SteelBrick','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(415,'Salesforce.com Validation Rules','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(416,'Salesforce.com Visualforce','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(417,'salesforce.com Wave','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(418,'Salesforce.com Webservices','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(419,'SAP ABAP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(420,'SAP ABAP HR','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(421,'SAP APO','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(422,'SAP ARIBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(423,'SAP BASIS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(424,'SAP BI BOBJ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(425,'SAP BI BPC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(426,'SAP BI BPC HANA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(427,'SAP BI BPC Planning & Consolidation','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(428,'SAP BI Data Integrator','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(429,'SAP BI Data Services','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(430,'SAP BI HANA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(431,'SAP BI Supply Chain Performance Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(432,'SAP BO','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(433,'SAP BO HANA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(434,'SAP BODI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(435,'SAP BODS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(436,'SAP BPC','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(437,'SAP Businessone','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(438,'SAP BW BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(439,'SAP CRM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(440,'SAP CRM Sales','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(441,'SAP EHS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(442,'SAP EWM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(443,'SAP FI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(444,'SAP FICA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(445,'SAP FICO','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(446,'SAP Fiori/UX','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(447,'SAP HANA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(448,'SAP HR','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(449,'SAP Hybris Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(450,'SAP Hybris Technical','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(451,'SAP IBP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(452,'SAP ISU','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(453,'SAP MDG','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(454,'SAP MDM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(455,'SAP MII','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(456,'SAP MM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(457,'SAP MM IM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(458,'SAP OpenText Content Management(xECM)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(459,'SAP PI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(460,'SAP PM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(461,'SAP PO','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(462,'SAP Portal','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(463,'SAP PP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(464,'SAP PS','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(465,'SAP QM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(466,'SAP S/4 HANA FI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(467,'SAP S/4 HANA SD','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(468,'SAP SD','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(469,'SAP SRM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(470,'SAP Successfactors','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(471,'SAP Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(472,'SAP TM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(473,'SAP UI5','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(474,'SAP UI5-FIORI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(475,'SAP Vistex','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(476,'SAP WebDynpro ABAP','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(477,'SAP WM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(478,'SAP XI-PI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(479,'SAS BI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(480,'SAS Data Mining','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(481,'SAS Enterprise Guide','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(482,'SAS Enterprise Miner','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(483,'Scala','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(484,'SCP/HCI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(485,'Scrum Master','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(486,'SDL Tridon','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(487,'Selenium Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(488,'Semoss','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(489,'Sencha','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(490,'Service Desk','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(491,'Service Now','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(492,'Servicenow Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(493,'Sharepoint Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(494,'Siebel Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(495,'Siebel Config','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(496,'SIEBEL EAI','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(497,'SIEBEL EIM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(498,'Siebel Internationalization/Localization','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(499,'Siebel Performance Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(500,'Siebel Product Configurator','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(501,'Siebel Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(502,'Sitecore','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(503,'EBS SOA Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(504,'SOAP Webservices','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(505,'API Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(506,'Solr Search','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(507,'Spark','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(508,'Splunk','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(509,'Spring Framework','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(510,'Sprinklr','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(511,'SQL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(512,'SQL DW','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(513,'SQL Server','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(514,'SQL Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(515,'Storage Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(516,'Struts Framework','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(517,'Swift','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(518,'Sybase','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(519,'System Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(520,'Tableau','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(521,'Talend Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(522,'Talend ETL','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(523,'Teradata','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(524,'Teradata Database','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(525,'Teradata Enterprise Data Warehouse','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(526,'Dev Ops Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(527,'Tibco','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(528,'Tririga','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(529,'UI Path ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(530,'Unix Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(531,'Unix Shell Scripting','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(532,'VB.Net','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(533,'VBA (Visual Basic For Applications)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(534,'Video Production','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(535,'Visual Design','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(536,'Vuforia','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(537,'WCF','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(538,'Web API Solutions','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(539,'Web Methods','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(540,'Webcenter Portal','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(541,'Websphere Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(542,'Websphere Process Server ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(543,'Windows Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(544,'Workday','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(545,'Workday Big Data','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(546,'Workday Financials','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(547,'Workday Functional','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(548,'Workday Human Capital Management','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(549,'Workfusion ','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(550,'Workfusion Testing','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(551,'WPF','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(552,'WWF (Windows Workflow Foundation)','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(553,'Xamarin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(554,'Snaplogic','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(555,'SAP SM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(556,'EBS OIM','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(557,'Postgre DBA','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(558,'Oracle PaaS Administration','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(559,'Oracle PaaS Security Admin','Active',NOW(),'dcodedev',NOW(),NULL,NULL),
(560,'Zuora','Active',NOW(),'dcodedev',NOW(),NULL,NULL);

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `dcode` ;
USE `dcode`;

-- -----------------------------------------------------
-- Table `elmah`.`elmah_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcode`.`elmah_error` (
  `ErrorId` CHAR(36) NOT NULL ,
  `Application` VARCHAR(60) NOT NULL ,
  `Host` VARCHAR(50) NOT NULL ,
  `Type` VARCHAR(100) NOT NULL ,
  `Source` VARCHAR(60) NOT NULL ,
  `Message` VARCHAR(500) NOT NULL ,
  `User` VARCHAR(50) NOT NULL ,
  `StatusCode` INT(10) NOT NULL ,
  `TimeUtc` DATETIME NOT NULL ,
  `Sequence` INT(10) NOT NULL AUTO_INCREMENT ,
  `AllXml` TEXT NOT NULL ,
  PRIMARY KEY (`Sequence`) ,
  UNIQUE INDEX `IX_ErrorId` (`ErrorId`(8) ASC) ,
  INDEX `IX_ELMAH_Error_App_Time_Seql` (`Application`(10) ASC, `TimeUtc` DESC, `Sequence` DESC) ,
  INDEX `IX_ErrorId_App` (`ErrorId`(8) ASC, `Application`(10) ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
CHECKSUM = 1
DELAY_KEY_WRITE = 1
ROW_FORMAT = DYNAMIC;


DELIMITER //

USE dcode//

CREATE PROCEDURE `dcode`.`elmah_GetErrorXml` (
  IN Id CHAR(36),
  IN App VARCHAR(60)
)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
    SELECT  `AllXml`
    FROM    `elmah_error`
    WHERE   `ErrorId` = Id AND `Application` = App;
END//

USE dcode//

CREATE PROCEDURE `dcode`.`elmah_GetErrorsXml` (
  IN App VARCHAR(60),
  IN PageIndex INT(10),
  IN PageSize INT(10),
  OUT TotalCount INT(10)
)
NOT DETERMINISTIC
READS SQL DATA
BEGIN
    
    SELECT  count(*) INTO TotalCount
    FROM    `elmah_error`
    WHERE   `Application` = App;

    SET @index = PageIndex * PageSize;
    SET @count = PageSize;
    SET @app = App;
    PREPARE STMT FROM '
    SELECT
        `ErrorId`,
        `Application`,
        `Host`,
        `Type`,
        `Source`,
        `Message`,
        `User`,
        `StatusCode`,
        CONCAT(`TimeUtc`, '' Z'') AS `TimeUtc`
    FROM
        `elmah_error` error
    WHERE
        `Application` = ?
    ORDER BY
        `TimeUtc` DESC,
        `Sequence` DESC
    LIMIT
        ?, ?';
    EXECUTE STMT USING @app, @index, @count;

END//

USE dcode//

CREATE PROCEDURE `dcode`.`elmah_LogError` (
    IN ErrorId CHAR(36), 
    IN Application varchar(60), 
    IN Host VARCHAR(30), 
    IN Type VARCHAR(100), 
    IN Source VARCHAR(60), 
    IN Message VARCHAR(500), 
    IN User VARCHAR(50), 
    IN AllXml TEXT, 
    IN StatusCode INT(10), 
    IN TimeUtc DATETIME
)
NOT DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    INSERT INTO `elmah_error` (
        `ErrorId`, 
        `Application`, 
        `Host`, 
        `Type`, 
        `Source`, 
        `Message`, 
        `User`, 
        `AllXml`, 
        `StatusCode`, 
        `TimeUtc`
    ) VALUES (
        ErrorId, 
        Application, 
        Host, 
        Type, 
        Source, 
        Message, 
        User, 
        AllXml, 
        StatusCode, 
        TimeUtc
    );
END//

DELIMITER ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


