//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCode.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_subscription
    {
        public int NOTIFICATION_SUBSCRIPTION_ID { get; set; }
        public int USER_ID { get; set; }
        public bool SUBSCRIPTION_STATUS { get; set; }
    
        public virtual user user { get; set; }
    }
}
