//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCode.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class suboffering
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int OfferingsId { get; set; }
        public string Practice_Email_Group { get; set; }
    
        public virtual offering offering { get; set; }

        public List<string> GetRmEmailsAsList()
        {
            return SplitEmailsToList(Practice_Email_Group);
        }

        public List<string> GetPracticeEmailGroupsAsList()
        {
            return SplitEmailsToList(Practice_Email_Group);
        }

        private List<string> SplitEmailsToList(string emailString)
        {
            return emailString?.Split(';')?.ToList();
        }
    }
}
