//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCode.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskapplicant
    {
        public int ID { get; set; }
        public int TASK_ID { get; set; }
        public int APPLICANT_ID { get; set; }
        public string STATEMENT_OF_PURPOSE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_DATE { get; set; }
        public Nullable<int> PROFICIENCY_ID { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
    
        public virtual proficiency proficiency { get; set; }
        public virtual user user { get; set; }
        public virtual task task { get; set; }
    }
}
