//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCode.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_points1
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public string @event { get; set; }
        public int points { get; set; }
        public System.DateTime created_date { get; set; }
        public int role_id { get; set; }
    
        public virtual user_role1 user_role { get; set; }
        public virtual user1 user { get; set; }
    }
}
